#!/bin/bash

DIR="$(dirname $0)"

if [ ! -f "$DIR/.venv" ]; then
    echo "ERROR: Virtual environment has not been created."
    exit 1
fi

if [ -z "$VIBER_CONF" ]; then
    export VIBER_CONF=/etc/viber/bot-command.conf
fi

source "$DIR/.venv"

python "$DIR/bot/command/bot.py" $*
