#!/usr/bin/env python3

import sys
from viber_command_bot.viber import config, viber

try:
    print('Un-registering webhook "{}" ... '.format(config['Viber']['webhook']),
          end='', flush=True)
    viber.unset_webhook()
    print('OK.')
except Exception as e:
    print('\nERROR: Failed to un-register bot: {}'.format(e))
    sys.exit(1)
sys.exit(0)
