#!/usr/bin/env python3

import sys
from viber_command_bot.viber import config, viber


try:
    print('Registering webhook "{}" ... '.format(config['Viber']['webhook']),
          end='', flush=True)
    viber.set_webhook(config['Viber']['webhook'])
    print('OK.')
except Exception as e:
    print('\nERROR: Failed to register bot: {}'.format(e))
    sys.exit(1)
sys.exit(0)
