#!/bin/bash

DIR="$(dirname $0)/.."

if [ ! -f "$DIR/.virtualenvrc" ]; then
    echo "ERROR: Virtual environment has not been created."
    exit 1
fi

source "$DIR/.virtualenvrc"

python "$DIR/bots/command/bot.py" "$@"
