#!/usr/bin/env python3

import sys
import time

from viber_command_bot.cache import cache, CacheError
from viber_command_bot.config import config
from viber_command_bot.messages import send_message
from viber_command_bot.flask.application import command_thread_target


def main():

    if not config.get('Viber', 'redis_channel'):
        print('FATAL: Redis channel is not configured')
        return 1

    try:
        cache.listen()
        print('Waiting for messages...\n')
        while True:
            message = cache.get_message()
            if message.get('message_type') == 'execute':
                command_thread_target(message.get('text'),
                                      message.get('output_format'),
                                      message.get('user_id'))
            else:
                show_message(message)
    except CacheError as e:
        print('FATAL: {}'.format(e))
        return 1
    except KeyboardInterrupt:
        print('Exiting...')

    return 0


def show_message(message):
    if not message:
        return
    print('[{date}] Message from {name}:\n{text}'.format(**message))
    if message.get('media'):
        print('{}'.format(message.get('media')))
    print()


if __name__ == '__main__':
    sys.exit(main())
